### ISSUE TITLE
Reflective Padding

### ISSUE THREAD

**Issue by alokwhitewolf** [wkentaro/chainer-cyclegan#1]
The original paper used reflective padding in it's generator network. Is there any way to replicate that through chainer?

**Comment by wkentaro** [comment]
You can use my PR: https://github.com/cupy/cupy/pull/1040
and changing mode='constant' to 'reflect' for F.pad like https://github.com/wkentaro/chainer-cyclegan/blob/master/chainer_cyclegan/models/generators.py#L16
